"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import { TestFlow } from "@/components/test/test-flow";
import { TestResultRouter } from "@/features/tests/TestResultRouter";
import { submitTestFlow } from "@/services/testSubmitService";
import { useTestResultPolling } from "@/hooks/useTestResultPolling";
import AIFailed from "@/components/custom/AIFailed";
import AIPreparing from "@/components/custom/AIPreparing";
import {
  type TestFromApi,
  type TestResultResponse,
  apiListTestResults,
} from "@/lib/api-client";
import { FlowState } from "@/components/test/types";

interface TestWithUi extends TestFromApi {
  categoryId: string;
  icon: React.ReactNode;
  description: string;
  locked: boolean;
  completed: boolean;
  alreadyTaken: boolean;
}

export interface ExploreTestOrchestratorProps {
  test: TestWithUi;
  isPremium: boolean;
  onClose: () => void;
  onboardingNext?: () => void;
}

export function ExploreTestOrchestrator({
  test,
  isPremium,
  onClose,
  onboardingNext,
}: ExploreTestOrchestratorProps) {
  const router = useRouter();
  const shellRef = useRef<HTMLDivElement>(null);

  const testId = test.id;
  const testTitle = test.title;
  const testCategory = test.category;
  const isAutoGenerated = Boolean(test.auto_generated);
  const isAlreadyTaken = Boolean(test.alreadyTaken || test.completed);

  const initialState: FlowState =
    isAlreadyTaken || isAutoGenerated ? "loading" : "questioning";

  const [orchestratorState, setOrchestratorState] =
    useState<FlowState>(initialState);
  const [submittedResultId, setSubmittedResultId] = useState<number | null>(
    null,
  );
  const [fetchedResult, setFetchedResult] = useState<TestResultResponse | null>(
    null,
  );

  const { result: polledResult } = useTestResultPolling(
    submittedResultId,
    orchestratorState === "processing",
    setOrchestratorState,
  );

  const completedResult = fetchedResult ?? polledResult;

  useEffect(() => {
    if (!isAutoGenerated) return;

    let cancelled = false;
    setOrchestratorState("loading");

    apiListTestResults(testId)
      .then((results) => {
        if (cancelled) return;
        if (results.length > 0) {
          setFetchedResult(results[0]);
          setOrchestratorState("completed");
          return;
        }
        setOrchestratorState("processing");
        return submitTestFlow({
          testId,
          testTitle,
          category: testCategory,
          questions: [],
          answers: {},
        }).then((resultId) => {
          if (!cancelled && resultId) setSubmittedResultId(resultId);
        });
      })
      .catch(() => {
        if (!cancelled) setOrchestratorState("failed");
      });

    return () => {
      cancelled = true;
    };
  }, [isAutoGenerated, testId, testTitle, testCategory]);

  useEffect(() => {
    if (!isAlreadyTaken || isAutoGenerated) return;

    let cancelled = false;
    setOrchestratorState("loading");

    apiListTestResults(testId)
      .then((results) => {
        if (!cancelled) {
          if (results.length > 0) {
            setFetchedResult(results[0]);
            setOrchestratorState("completed");
          } else {
            setOrchestratorState("questioning");
          }
        }
      })
      .catch(() => {
        if (!cancelled) {
          setOrchestratorState("failed");
        }
      });

    return () => {
      cancelled = true;
    };
  }, [isAlreadyTaken, isAutoGenerated, testId]);

  const handleTestFlowComplete = useCallback((resultId: number) => {
    setSubmittedResultId(resultId);
    setOrchestratorState("processing");
  }, []);

  const handleRetake = async () => {
    if (!isPremium) {
      try {
        const results = await apiListTestResults();
        const completedCount = new Set(results.filter(r => r.status === 'completed').map(r => r.test_id)).size;
        if (completedCount >= 8 && !isAlreadyTaken) {
           onClose();
           return;
        }
      } catch (e) {
        console.error("Failed to check limits", e);
      }
    }

    setFetchedResult(null);
    setSubmittedResultId(null);
    if (isAutoGenerated) {
      setOrchestratorState("processing");
      submitTestFlow({
        testId,
        testTitle,
        category: testCategory,
        questions: [],
        answers: {},
      })
        .then((resultId) => {
          setSubmittedResultId(resultId);
        })
        .catch(() => setOrchestratorState("failed"));
    } else {
      setOrchestratorState("questioning");
    }
  };

  if (orchestratorState === "completed" && completedResult) {
    return (
      <TestResultRouter
        testId={testId}
        testTitle={testTitle}
        category={testCategory}
        result={completedResult}
        onBack={onClose}
        onRetake={handleRetake}
        shellRef={shellRef}
        onboardingNext={onboardingNext}
        onLogout={() => router.push("/welcome")}
      />
    );
  }

  if (orchestratorState === "failed") {
    return <AIFailed onboardingNext={onboardingNext} onClose={onClose} />;
  }

  if (orchestratorState === "processing" || orchestratorState === "loading") {
    return <AIPreparing />;
  }

  return (
    <TestFlow
      testId={testId}
      testTitle={testTitle}
      category={testCategory}
      onClose={onClose}
      autoGenerated={test.auto_generated}
      onComplete={handleTestFlowComplete}
    />
  );
}
