"use client";

import { cn } from "@/lib/utils";
import { ReactNode } from "react";

interface TestCardProps {
  test: {
    id: number;
    title: string;
    category: string;
    locked: boolean;
    alreadyTaken: boolean;
    questions: number;
    completed?: boolean;
    icon: ReactNode;
    autoGenerated?: boolean;
  };
  isSelected: boolean;
  onSelect: () => void;
}

export function TestCard({ test, onSelect }: TestCardProps) {
  return (
    <button
      onClick={onSelect}
      className={cn(
        `
        relative
        rounded-[10px]
        border
        transition-all
        duration-300
        flex
        flex-col
        items-center
        gap-2

        px-1.5
        py-3
        max-h-[120px]
        min-w-[100px]
        sm:min-w-[110px]
        max-w-[125px]

        min-h-[100px]
        sm:min-h-[110px]
        sm:px-3
        sm:py-3

        md:min-h-[120px]
        md:px-4
        `,
        test.alreadyTaken
          ? "border-[#F2D08C] cursor-pointer"
          : "border-[#F2D08C66] cursor-not-allowed",
      )}
    >
      <div
        className={cn(
          "flex items-center justify-center max-w-[68px] h-[68px]",
          test.alreadyTaken ? "opacity-100" : "opacity-40",
        )}
      >
        {test.icon}
      </div>

      <h3
        style={{
          fontFamily: "var(--font-gotham)",
          fontWeight: "300",
          lineHeight: "1.2",
        }}
        className={cn(
          "text-center text-white text-[11px]",
          test.alreadyTaken
            ? "opacity-100 font-medium"
            : "opacity-60 font-normal",
        )}
      >
        {test.title}
      </h3>
    </button>
  );
}
