"use client";

import { useState, useEffect, useMemo, useCallback, useRef } from "react";
import { TestCard } from "@/components/cards/test-card";
import { TestFlow, type TestFlowProps } from "@/components/test/test-flow";
import { TestResultView } from "@/components/test/test-result-view";
import {
  AstrologyChartResultView,
  StarseedOriginResult,
  ChakraAlignmentResult,
} from "@/components/test/result-view";
import { SubscriptionModal } from "@/components/modals/subscription-modal";
import { TestIntro } from "../modals/test-intro";
import {
  apiFetchTests,
  apiListTestResults,
  apiFetchAstrologyChart,
  type AstrologyChartResponse,
  type TestFromApi,
  type TestResultResponse,
} from "@/lib/api-client";
import { getTestUi } from "@/lib/constants/testUiMap";
import { useRouter } from "next/navigation";

interface ExplorePageProps {
  isPremium: boolean;
}

interface TestWithUi extends TestFromApi {
  categoryId: string;
  icon: React.ReactNode;
  description: string;
  locked: boolean;
  completed: boolean;
  alreadyTaken: boolean;
}

export function ExplorePage({ isPremium }: ExplorePageProps) {
  const router = useRouter();
  const shellRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const [testsResponse, setTestsResponse] = useState<{
    user_is_premium: boolean;
    tests: TestFromApi[];
  } | null>(null);
  const [testsError, setTestsError] = useState<string | null>(null);
  const [selectedTest, setSelectedTest] = useState<number | null>(null);
  const [activeTest, setActiveTest] = useState<{
    id: number;
    title: string;
    category: string;
    autoGenerated?: boolean;
  } | null>(null);
  const [viewingResult, setViewingResult] = useState<number | null>(null);
  const [viewingResultData, setViewingResultData] = useState<
    TestResultResponse | null | undefined
  >(undefined);
  const [showSubscriptionModal, setShowSubscriptionModal] = useState(false);
  const [lockedTestForIntro, setLockedTestForIntro] = useState<{
    title: string;
    description: string;
  } | null>(null);

  const [astrologyChart, setAstrologyChart] =
    useState<AstrologyChartResponse | null>(null);
  const [autoResultError, setAutoResultError] = useState<string | null>(null);
  const [autoResultLoading, setAutoResultLoading] = useState(false);

  const refetchTests = useCallback(() => {
    setTestsError(null);
    apiFetchTests()
      .then((data) =>
        setTestsResponse({
          user_is_premium: data.user_is_premium,
          tests: data.tests,
        }),
      )
      .catch((e) =>
        setTestsError(e instanceof Error ? e.message : "Failed to load tests"),
      );
  }, []);

  useEffect(() => {
    let cancelled = false;
    setTestsError(null);
    apiFetchTests()
      .then((data) => {
        if (!cancelled)
          setTestsResponse({
            user_is_premium: data.user_is_premium,
            tests: data.tests,
          });
      })
      .catch((e) => {
        if (!cancelled)
          setTestsError(
            e instanceof Error ? e.message : "Failed to load tests",
          );
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const userIsPremium = testsResponse?.user_is_premium ?? isPremium;

  const tests: TestWithUi[] = useMemo(() => {
    if (!testsResponse?.tests) return [];
    return testsResponse.tests.map((t) => {
      const ui = getTestUi(t.id);
      return {
        ...t,
        categoryId: t.category_id,
        icon: ui.icon,
        description: ui.description,
        locked: t.premium && !userIsPremium,
        completed: t.already_taken,
        alreadyTaken: t.already_taken,
      };
    });
  }, [testsResponse, userIsPremium]);

  const categories = useMemo(() => {
    return Array.from(
      new Map(
        tests.map((t) => [
          t.categoryId,
          { id: t.categoryId, label: t.category },
        ]),
      ).values(),
    );
  }, [tests]);

  const handleTestSelect = (test: TestWithUi) => {
    if (test.locked) {
      setLockedTestForIntro({
        title: test.title,
        description: test.description,
      });
      return;
    }
    // Auto-generated: only Astrology Chart (1) uses direct fetch; all others go through TestFlow → compute + LLM → result.
    if (test.auto_generated && test.id === 1) {
      setViewingResult(test.id);
      setViewingResultData(undefined);
      setAutoResultError(null);
      setAutoResultLoading(true);
      setAstrologyChart(null);
      apiFetchAstrologyChart()
        .then((chart) => {
          setAstrologyChart(chart);
        })
        .catch((e) =>
          setAutoResultError(
            e instanceof Error ? e.message : "Failed to load astrology chart",
          ),
        )
        .finally(() => setAutoResultLoading(false));
      return;
    }
    if (test.alreadyTaken || test.completed) {
      setViewingResult(test.id);
      setViewingResultData(undefined);
      apiListTestResults(test.id)
        .then((results) => {
          if (results.length > 0) setViewingResultData(results[0]);
          else setViewingResultData(null);
        })
        .catch(() => setViewingResultData(null));
      return;
    }
    setActiveTest({
      id: test.id,
      title: test.title,
      category: test.category,
      autoGenerated: test.auto_generated,
    });
  };

  if (activeTest) {
    const testFlowProps: TestFlowProps = {
      testId: activeTest.id,
      testTitle: activeTest.title,
      category: activeTest.category,
      autoGenerated: activeTest.autoGenerated,
      onClose: () => {
        setActiveTest(null);
        refetchTests();
      },
    };
    return <TestFlow {...testFlowProps} />;
  }

  if (viewingResult !== null) {
    const test = tests.find((t) => t.id === viewingResult);
    const onBackResult = () => {
      setViewingResult(null);
      setViewingResultData(undefined);
      setAstrologyChart(null);
      setAutoResultError(null);
      setAutoResultLoading(false);
    };
    if (!test) {
      setViewingResult(null);
      setViewingResultData(undefined);
      setAstrologyChart(null);
      setAutoResultError(null);
      setAutoResultLoading(false);
    } else if (test.id === 3) {
      return (
        <StarseedOriginResult testTitle={test.title} onBack={onBackResult} />
      );
    } else if (test.id === 13) {
      if (viewingResultData === undefined) {
        return (
          <div className="pb-24 flex items-center justify-center min-h-[200px]">
            <p className="text-[#F2D08C] font-[325]">Loading your result…</p>
          </div>
        );
      }
      return (
        <ChakraAlignmentResult
          testTitle={test.title}
          onBack={onBackResult}
          content={viewingResultData?.llm_result_json ?? undefined}
        />
      );
    } else if (test.id === 1) {
      if (autoResultLoading || (!astrologyChart && !autoResultError)) {
        return (
          <div className="pb-24 flex items-center justify-center min-h-[200px]">
            <p className="text-[#F2D08C] font-[325]">Loading your chart…</p>
          </div>
        );
      }
      if (autoResultError || !astrologyChart) {
        return (
          <div className="pb-24 flex flex-col items-center justify-center min-h-[200px] px-4 text-center">
            <p className="text-[#F2D08C] font-[325] mb-3">
              {autoResultError ?? "Could not load your astrology chart."}
            </p>
            <button
              type="button"
              onClick={onBackResult}
              className="px-4 py-2 rounded-md bg-[#F2D08C] text-black text-sm"
            >
              Close
            </button>
          </div>
        );
      }
      return (
        <AstrologyChartResultView
          chart={astrologyChart}
          onClose={onBackResult}
          shellRef={shellRef}
          onLogout={() => router.push("/welcome")}
        />
      );
    } else {
      if (!test.auto_generated && viewingResultData === undefined) {
        return (
          <div className="pb-24 flex items-center justify-center min-h-[200px]">
            <p className="text-[#F2D08C] font-[325]">Loading your result…</p>
          </div>
        );
      }
      return (
        <TestResultView
          testId={test.id}
          testTitle={test.title}
          category={test.category}
          onBack={onBackResult}
          result={viewingResultData ?? undefined}
        />
      );
    }
  }

  if (testsError) {
    return (
      <div className="pb-24 px-4 text-center">
        <p className="text-[#F2D08C] font-[325] mb-2">{testsError}</p>
        <button
          type="button"
          onClick={() => window.location.reload()}
          className="text-white underline"
        >
          Retry
        </button>
      </div>
    );
  }

  if (!testsResponse) {
    return (
      <div className="pb-24 flex items-center justify-center min-h-[200px]">
        <p className="text-[#F2D08C] font-[325]">Loading tests…</p>
      </div>
    );
  }

  return (
    <div className="pb-16 space-y-6">
      <div className="text-center">
        <h1
          style={{
            fontFamily: "var(--font-gotham)",
            lineHeight: "22px",
          }}
          className="text-[15px] font-bold text-[#FFFFFF]"
        >
          Feel the missing pieces
        </h1>
        <p
          style={{
            fontFamily: "var(--font-gotham)",
            lineHeight: "22px",
          }}
          className="text-[15px] font-[100] text-[#FFFFFF]"
        >
          Each card reveals a layer of your unique self
        </p>
      </div>

      {categories.map((cat) => {
        const categoryTests = tests.filter((t) => t.categoryId === cat.id);
        return (
          <div key={cat.id} className="space-y-4">
            <h3
              style={{
                fontFamily: "var(--font-gotham)",
                lineHeight: "22px",
              }}
              className="text-[21px] text-left text-[#F2D08C] font-[325]"
            >
              {cat.label}
            </h3>

            <div className="grid grid-cols-3 gap-[9px]">
              {categoryTests.map((test) => (
                <TestCard
                  key={test.id}
                  test={{
                    id: test.id,
                    title: test.title,
                    category: test.category,
                    locked: test.locked,
                    alreadyTaken: test.alreadyTaken,
                    questions: test.questions,
                    completed: test.completed,
                    icon: test.icon,
                    autoGenerated: test.auto_generated,
                  }}
                  isSelected={selectedTest === test.id}
                  onSelect={() => {
                    setSelectedTest(test.id);
                    handleTestSelect(test);
                  }}
                />
              ))}
            </div>
          </div>
        );
      })}

      {lockedTestForIntro && (
        <TestIntro
          isPremium={userIsPremium}
          testTitle={lockedTestForIntro.title}
          testDescription={lockedTestForIntro.description}
          onClose={() => setLockedTestForIntro(null)}
          onUpgrade={() => {
            setLockedTestForIntro(null);
            setShowSubscriptionModal(true);
          }}
          onStart={() => setLockedTestForIntro(null)}
        />
      )}

      {showSubscriptionModal && (
        <SubscriptionModal
          onClose={() => setShowSubscriptionModal(false)}
          onUpgrade={() => setShowSubscriptionModal(false)}
        />
      )}
    </div>
  );
}
