"use client";

import { useEffect, useMemo, useState } from "react";
import {
  apiGetSynthesis,
  apiListTestResults,
  type SynthesisResponse,
} from "@/lib/api-client";
import { getTestUi } from "@/lib/constants/testUiMap";
import { TestCard } from "@/components/cards/test-card";

interface SynthesisPageProps {
  isPremium: boolean;
}

const SYNTHESIS_FULL_MIN = 6;
const TOTAL_TEST_COUNT = 24;

export function SynthesisPage({ isPremium: _isPremium }: SynthesisPageProps) {
  const [synthesis, setSynthesis] = useState<
    SynthesisResponse | null | undefined
  >(undefined);
  const [results, setResults] = useState<
    { test_id: number; test_title: string }[]
  >([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setError(null);
    apiGetSynthesis()
      .then((data) => {
        if (!cancelled) setSynthesis(data ?? null);
      })
      .catch((e) => {
        if (!cancelled) {
          setSynthesis(null);
          setError(e instanceof Error ? e.message : "Failed to load synthesis");
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    let cancelled = false;
    apiListTestResults()
      .then((list) => {
        if (cancelled) return;
        const completed = list.filter((r) => r.status === "completed");
        const byId = new Map<number, { test_id: number; test_title: string }>();
        completed.forEach((r) => {
          if (!byId.has(r.test_id))
            byId.set(r.test_id, {
              test_id: r.test_id,
              test_title: r.test_title,
            });
        });
        setResults(Array.from(byId.values()));
      })
      .catch(() => {
        if (!cancelled) setResults([]);
      });
    return () => {
      cancelled = true;
    };
  }, [synthesis?.completed_count]);

  const completedTests = useMemo(
    () =>
      results.map((r) => ({
        id: r.test_id,
        title: r.test_title,
        category: "",
        categoryId: "",
        icon: getTestUi(r.test_id).icon,
        locked: false,
        alreadyTaken: true,
        completed: true,
        questions: 0,
        auto_generated: false,
      })),
    [results],
  );

  const completedCount =
    synthesis?.completed_count ?? (results.length > 0 ? results.length : 0);
  const isFull = synthesis?.type === "full";
  const progress =
    TOTAL_TEST_COUNT > 0 ? Math.min(completedCount / TOTAL_TEST_COUNT, 1) : 0;
  const result = synthesis?.result ?? {};

  return (
    <div
      className="pb-16 space-y-4 text-white"
      style={{ fontFamily: "var(--font-gotham)" }}
    >
      <div className="mb-3 px-[28px] relative">
        <div className="h-[15px] rounded-full bg-transparent border border-[#F2D08C]/50 overflow-hidden">
          <div
            className="h-full rounded-full transition-[width] duration-300"
            style={{
              width: `${progress * 100}%`,
              backgroundColor: "#F2D08C",
            }}
          />
        </div>
        <p className="absolute right-10 top-1/2 -translate-y-1/2 text-white text-[10px] font-[400] z-10 pointer-events-none">
          {completedCount}/{TOTAL_TEST_COUNT}
        </p>
      </div>

      <div className="text-center space-y-3">
        <h1 className="text-[21px] font-light text-white">
          {isFull ? "Your Full Synthesis" : "Your Synthesis"}
        </h1>
        {synthesis && completedTests.length > 0 && (
          <div className="w-full overflow-x-auto no-scrollbar">
            <div className="flex items-center justify-center gap-[9px] min-w-max snap-x snap-mandatory">
              {completedTests.map((test) => (
                <div key={test.id} className="flex-shrink-0 snap-start h-auto">
                  <TestCard
                    test={{
                      id: test.id,
                      title: test.title,
                      category: test.category,
                      locked: test.locked,
                      alreadyTaken: true,
                      questions: test.questions,
                      completed: true,
                      icon: test.icon,
                      autoGenerated: test.auto_generated,
                    }}
                    isSelected={false}
                    onSelect={() => {}}
                  />
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {synthesis === undefined && !error && (
        <div className="px-[28px] py-8 text-center text-[#F2D08C] font-[325]">
          Loading your synthesis…
        </div>
      )}

      {error && (
        <div className="px-[28px] py-4 text-center text-red-400 text-sm">
          {error}
        </div>
      )}

      {synthesis === null && !error && (
        <section className="space-y-4 px-[28px] text-left">
          <h2 className="font-[400] text-[15px] text-[#FFFFFF] pt-2">
            Unlock your synthesis
          </h2>
          <p className="text-[13px] font-[400] text-[#F2D08C]">
            Complete at least 3 onboarding tests to generate a preview
            synthesis. It will be stored and shown here when you return.
            Complete 6 tests and upgrade to premium to unlock your full
            portrait.
          </p>
          <p className="text-[13px] font-[300] text-[#9ca3af]">
            Go to Explore to take more tests.
          </p>
        </section>
      )}

      {synthesis && result && (
        <section className="space-y-4 px-[28px] text-left">
          {result.youAre && (
            <>
              <h2 className="font-[400] text-[13px] text-[#FFFFFF] pt-1">
                You Are
              </h2>
              <p className="text-[13px] font-[400] text-[#F2D08C]">
                {result.youAre}
              </p>
            </>
          )}

          {(result.sureThings?.length ?? 0) > 0 && (
            <>
              <h2 className="font-[400] text-[15px] text-[#FFFFFF] pt-3">
                Sure things
              </h2>
              <p className="text-[13px] font-[400] text-[#F2D08C] mb-2">
                Patterns that stand out across your tests
              </p>
              <div className="flex items-center gap-1 flex-wrap">
                {result.sureThings!.map((item, i) => (
                  <span
                    key={i}
                    className="text-[#F2D08C] px-1.5 border border-[#F2D08C]/50 rounded-[10px] text-[13px] font-[300]"
                  >
                    {item}
                  </span>
                ))}
              </div>
            </>
          )}

          {result.identitySummary && (
            <>
              <h2 className="font-[400] text-[15px] text-[#FFFFFF] pt-3">
                Your identity
              </h2>
              <p className="text-[13px] font-[300] text-[#E7E7E7] border-l-2 border-[#F2D08C66] pl-1.5">
                {result.identitySummary}
              </p>
            </>
          )}

          {(result.growthAreas?.length ?? 0) > 0 && (
            <>
              <h2 className="font-[400] text-[15px] text-[#FFFFFF] pt-3">
                Growth areas
              </h2>
              <div className="flex items-center gap-1 flex-wrap">
                {result.growthAreas!.map((item, i) => (
                  <span
                    key={i}
                    className="text-[#D9D9D9] px-1.5 border border-[#D9D9D9]/50 rounded-[10px] text-[13px] font-[300]"
                  >
                    {item}
                  </span>
                ))}
              </div>
            </>
          )}

          {result.nextFocus && (
            <>
              <h2 className="font-[400] text-[15px] text-[#FFFFFF] pt-3">
                Next focus
              </h2>
              <p className="text-[13px] font-[400] text-[#F2D08C]">
                {result.nextFocus}
              </p>
            </>
          )}

          {isFull && (result.themes?.length ?? 0) > 0 && (
            <>
              <h2 className="font-[400] text-[15px] text-[#FFFFFF] pt-3">
                Themes
              </h2>
              <div className="flex items-center gap-1 flex-wrap">
                {result.themes!.map((item, i) => (
                  <span
                    key={i}
                    className="text-[#F2D08C] px-1.5 border border-[#F2D08C]/50 rounded-[10px] text-[13px] font-[300]"
                  >
                    {item}
                  </span>
                ))}
              </div>
            </>
          )}

          {isFull && (result.strengths?.length ?? 0) > 0 && (
            <>
              <h2 className="font-[400] text-[15px] text-[#FFFFFF] pt-3">
                Core strengths
              </h2>
              <div className="flex items-center gap-1 flex-wrap">
                {result.strengths!.map((item, i) => (
                  <span
                    key={i}
                    className="text-[#D9D9D9] px-1.5 border border-[#D9D9D9]/50 rounded-[10px] text-[13px] font-[300]"
                  >
                    {item}
                  </span>
                ))}
              </div>
            </>
          )}

          {isFull && (result.shadowPatterns?.length ?? 0) > 0 && (
            <>
              <h2 className="font-[400] text-[15px] text-[#FFFFFF] pt-3">
                Patterns to be aware of
              </h2>
              <div className="flex items-center gap-1 flex-wrap">
                {result.shadowPatterns!.map((item, i) => (
                  <span
                    key={i}
                    className="text-[#9ca3af] px-1.5 border border-[#9ca3af]/50 rounded-[10px] text-[13px] font-[300]"
                  >
                    {item}
                  </span>
                ))}
              </div>
            </>
          )}
        </section>
      )}
    </div>
  );
}
