"use client";

import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import AppBar from "../navigation/appBar";
import {
  apiFetchTestQuestions,
} from "@/lib/api-client";
import { useQuestionFlow } from "@/hooks/useQuestionFlow";
import { submitTestFlow } from "@/services/testSubmitService";
import { FlowState, MappedQuestion, mapApiQuestionToLocal } from "./types";
import AIPreparing from "../custom/AIPreparing";
import QuestionsLoading from "../custom/QuestionsLoading";

const GOLD = "#F2D08C";

function getOptions(
  q: MappedQuestion,
  answers: Record<number, string | number | string[]>,
): string[] {
  if (q.options_from_question_id != null) {
    const src = answers[q.options_from_question_id];
    if (Array.isArray(src)) return src as string[];
    return [];
  }
  return q.options ?? [];
}

export interface TestFlowProps {
  testId: number;
  testTitle: string;
  category: string;
  onClose: () => void;
  onboardingNext?: () => void;
  autoGenerated?: boolean;
  onComplete?: (resultId: number) => void;
}

export function TestFlow({
  testId,
  testTitle,
  category,
  onClose,
  autoGenerated,
  onComplete,
}: TestFlowProps) {
  const router = useRouter();
  const shellRef = useRef<HTMLDivElement>(null);
  const [questions, setQuestions] = useState<MappedQuestion[]>([]);
  const [flowState, setFlowState] = useState<FlowState>("loading");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const isQuestionlessComputedTest =
    Boolean(autoGenerated) ||
    testId === 2 ||
    testId === 5 ||
    testId === 6;

  const {
    step,
    currentQuestion,
    activeQuestions,
    progressPercent,
    isAnswered,
    answers,
    goNext,
    setAnswer,
  } = useQuestionFlow(questions);

  useEffect(() => {
    let cancelled = false;
    setFlowState("loading");
    setErrorMsg(null);

    apiFetchTestQuestions(testId)
      .then((list) => {
        if (!cancelled) {
          setQuestions(list.map(mapApiQuestionToLocal));
          setFlowState("questioning");
        }
      })
      .catch((e) => {
        if (!cancelled) {
          setErrorMsg(
            e instanceof Error ? e.message : "Failed to load questions",
          );
          setFlowState("failed");
        }
      });
    return () => {
      cancelled = true;
    };
  }, [testId]);

  useEffect(() => {
    if (
      isQuestionlessComputedTest &&
      flowState === "questioning" &&
      questions.length === 0
    ) {
      setFlowState("submitting");
      submitTestFlow({
        testId,
        testTitle,
        category,
        questions: [],
        answers: {},
      })
        .then((resultId) => {
          setFlowState("processing");
          onComplete?.(resultId);
        })
        .catch((e) => {
          setErrorMsg(e instanceof Error ? e.message : "Submit failed");
          setFlowState("failed");
        });
    }
  }, [
    isQuestionlessComputedTest,
    flowState,
    questions.length,
    testId,
    testTitle,
    category,
    onComplete,
  ]);

  const handleBack = () => onClose();

  const handleContinue = () => {
    if (!currentQuestion) return;
    if (step === activeQuestions.length - 1) {
      setFlowState("submitting");
      submitTestFlow({
        testId,
        testTitle,
        category,
        questions,
        answers,
      })
        .then((resultId) => {
          setFlowState("processing");
          onComplete?.(resultId);
        })
        .catch((e) => {
          setErrorMsg(e instanceof Error ? e.message : "Submit failed");
          setFlowState("failed");
        });
    } else {
      goNext();
    }
  };

  if (flowState === "completed") {
    return null;
  }

  if (flowState === "processing") {
    return <AIPreparing />;
  }

  if (flowState === "loading") {
    return <QuestionsLoading />;
  }

  if (flowState === "failed") {
    return (
      <div className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black px-6 gap-4">
        <p className="text-[#F2D08C] font-[325] text-center">{errorMsg}</p>
        <Button onClick={handleBack} className="bg-[#F2D08C] text-black">
          Go back
        </Button>
      </div>
    );
  }

  if (
    !isQuestionlessComputedTest &&
    (questions.length === 0 || activeQuestions.length === 0)
  ) {
    return (
      <div className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black px-6 gap-4">
        <p className="text-[#F2D08C] font-[325] text-center">
          This test has no questions yet.
        </p>
        <Button onClick={handleBack} className="bg-[#F2D08C] text-black">
          Go back
        </Button>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-white px-0 sm:px-4">
      <div
        ref={shellRef}
        style={{ fontFamily: "var(--font-gotham)" }}
        className="relative pt-4 w-full h-dvh sm:h-auto sm:min-h-0 sm:max-w-[450px] sm:aspect-[9/20] bg-black overflow-hidden flex flex-col items-center text-center pb-4"
      >
        <AppBar
          shellRef={shellRef}
          handleLogout={() => router.push("/welcome")}
          handleBack={handleBack}
        />

        <div className="flex flex-col flex-1 overflow-y-auto w-full">
          <div className="flex flex-col px-[32px] flex-1 w-full">
            <p
              className="mt-8 text-center text-white text-[21px] font-[300]"
              style={{ lineHeight: "33px" }}
            >
              {testTitle}
            </p>

            <div className="my-[27px] relative w-full">
              <div className="h-[17px] w-full rounded-full border border-[#F2D08C] overflow-hidden">
                <div
                  className="h-full transition-all duration-300"
                  style={{
                    width: `${progressPercent}%`,
                    backgroundColor: GOLD,
                  }}
                />
              </div>
              <span className="absolute right-2 top-1/2 -translate-y-1/2 text-white text-[10px]">
                {step + 1}/{activeQuestions.length}
              </span>
            </div>

            <h2
              className="text-center text-[21px] mb-6 text-[#F2D08C] font-[400]"
              style={{ lineHeight: "33px" }}
            >
              {currentQuestion?.question}
            </h2>

            <div className="flex-1 w-full space-y-4">
              {currentQuestion?.type === "text" && (
                <textarea
                  className="w-full h-[160px] rounded-xl bg-[#FFFFFF1C] border border-[#FFFFFF]/50 outline-none text-white p-4"
                  value={(answers[currentQuestion.id] as string) ?? ""}
                  onChange={(e) =>
                    setAnswer(currentQuestion.id, e.target.value)
                  }
                  placeholder="Type your answer…"
                />
              )}

              {(currentQuestion?.type === "date" ||
                currentQuestion?.type === "time") && (
                <input
                  type={currentQuestion.type}
                  className="w-full h-12 rounded-xl bg-[#FFFFFF1C] border border-white/50 outline-none text-white px-4"
                  value={(answers[currentQuestion.id] as string) ?? ""}
                  onChange={(e) =>
                    setAnswer(currentQuestion.id, e.target.value)
                  }
                />
              )}

              {currentQuestion?.type === "color" && (
                <div className="space-y-3">
                  {currentQuestion.options!.map((color) => (
                    <button
                      key={color}
                      onClick={() => setAnswer(currentQuestion.id, color)}
                      className="w-full h-[48px] rounded-lg text-left px-4 font-[300] text-[15px]"
                      style={{
                        backgroundColor: color.toLowerCase(),
                        color:
                          color === "Yellow" || color === "White"
                            ? "black"
                            : "white",
                        opacity:
                          answers[currentQuestion.id] === color ? 1 : 0.6,
                      }}
                    >
                      {color}
                    </button>
                  ))}
                </div>
              )}

              {currentQuestion?.type === "single_choice" &&
                (() => {
                  const opts = getOptions(currentQuestion, answers);
                  return opts.length > 0 ? (
                    <div className="space-y-4">
                      {opts.map((opt) => (
                        <button
                          key={opt}
                          onClick={() => setAnswer(currentQuestion.id, opt)}
                          className={`w-full min-h-[56px] rounded-xl border text-left px-4 py-3 transition ${
                            answers[currentQuestion.id] === opt
                              ? "bg-[#F2D08C] text-black border-[#F2D08C]"
                              : "border-[#5A4A2A] text-white"
                          }`}
                        >
                          {opt}
                        </button>
                      ))}
                    </div>
                  ) : (
                    <p className="text-white/70 text-sm">
                      Answer the previous question first.
                    </p>
                  );
                })()}

              {currentQuestion?.type === "multiple_choice" &&
                (() => {
                  const opts = getOptions(currentQuestion, answers);
                  const selected =
                    (answers[currentQuestion.id] as string[]) ?? [];
                  const maxSel = currentQuestion.max_selections ?? undefined;
                  return opts.length > 0 ? (
                    <div className="space-y-3">
                      {maxSel != null && (
                        <p className="text-[#F2D08C] text-sm">
                          Select exactly {maxSel} (selected: {selected.length})
                        </p>
                      )}
                      {opts.map((opt) => {
                        const checked = selected.includes(opt);
                        const atMax =
                          maxSel != null &&
                          selected.length >= maxSel &&
                          !checked;
                        return (
                          <label
                            key={opt}
                            className={`flex items-center gap-3 w-full min-h-[56px] rounded-xl border px-4 py-3 cursor-pointer transition ${
                              checked
                                ? "bg-[#F2D08C] text-black border-[#F2D08C]"
                                : atMax
                                  ? "border-[#5A4A2A] text-white opacity-60 cursor-not-allowed"
                                  : "border-[#5A4A2A] text-white"
                            }`}
                            onClick={() => {
                              if (atMax) return;
                              const next = checked
                                ? selected.filter((x) => x !== opt)
                                : maxSel != null && selected.length >= maxSel
                                  ? selected
                                  : [...selected, opt];
                              setAnswer(currentQuestion.id, next);
                            }}
                          >
                            <span className="text-white">{opt}</span>
                          </label>
                        );
                      })}
                    </div>
                  ) : (
                    <p className="text-white/70 text-sm">
                      Answer the previous question first.
                    </p>
                  );
                })()}

              {currentQuestion?.type === "slider" &&
                (() => {
                  const value =
                    (answers[currentQuestion.id] as number) ??
                    Math.round(
                      (currentQuestion.slider_min +
                        currentQuestion.slider_max) /
                        2,
                    );
                  const range =
                    currentQuestion.slider_max - currentQuestion.slider_min ||
                    1;
                  const pct =
                    ((value - currentQuestion.slider_min) / range) * 100;
                  return (
                    <div className="px-2">
                      <input
                        type="range"
                        min={currentQuestion.slider_min}
                        max={currentQuestion.slider_max}
                        value={value}
                        onChange={(e) =>
                          setAnswer(currentQuestion.id, Number(e.target.value))
                        }
                        className="w-full custom-range"
                        style={{ "--value": pct } as React.CSSProperties}
                      />
                      <p className="text-[#F2D08C] text-sm mt-2">{value}</p>
                    </div>
                  );
                })()}
            </div>
          </div>

          {errorMsg && flowState === "submitting" && (
            <p className="text-red-400 text-sm px-6 mb-4">{errorMsg}</p>
          )}

          <div className="px-[32px] w-full mt-auto pt-8">
            <Button
              className="w-full text-[16px] rounded-[10px] h-[67px] transition-opacity disabled:opacity-50"
              style={{
                backgroundColor: GOLD,
                color: "black",
                fontFamily: "var(--font-arp80)",
                fontWeight: "400",
                lineHeight: "33px",
              }}
              disabled={!isAnswered() || flowState === "submitting"}
              onClick={handleContinue}
            >
              {flowState === "submitting"
                ? "Submitting…"
                : step === activeQuestions.length - 1
                  ? "Submit"
                  : "Continue"}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
